name: ClusterFuzzLite batch fuzzing
on:
  schedule:
    - cron: '*/10 * * * *'  # Every hour.
permissions: read-all
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
        # Override this with the sanitizers you want.
        # - undefined
        # - memory
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: jvm
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 120
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}
          # Optional but recommended: For storing certain artifacts from fuzzing.
          # See later section on "Git repo for storage".
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jtpereyda/clusterfuzzlite-demo-corpus.git
          storage-repo-branch: main   # Optional. Defaults to "main"
          storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
